name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: make install

      - name: Lint
        run: make lint

      - name: Run ETL and Query
        run: |
          python main.py

      - name: Test
        run: make test

      - name: Format
        run: make format

      - name: Deploy
        run: make deploy
